exports.bossTimers = [
    // Define message ID's of boss channels.

    // Apophis
    { key: `apophisChannel1`, messageID: `` },
    { key: `apophisChannel2`, messageID: `` },
    { key: `apophisChannel3`, messageID: `` },
    { key: `apophisChannel4`, messageID: `` },
    { key: `apophisChannel5`, messageID: `` },
    { key: `apophisChannel6`, messageID: `` },
    { key: `apophisChannel7`, messageID: `` },
    { key: `apophisChannel8`, messageID: `` },
    { key: `apophisChannel9`, messageID: `` },
    { key: `apophisChannel10`, messageID: `` },
    { key: `apophisChannel11`, messageID: `` },
    { key: `apophisChannel12`, messageID: `` },
    { key: `apophisChannel13`, messageID: `` },
    { key: `apophisChannel14`, messageID: `` },
    { key: `apophisChannel15`, messageID: `` },
    { key: `apophisChannel16`, messageID: `` },

    // Barbarossa
    { key: `barbarossaChannel1`, messageID: `` },
    { key: `barbarossaChannel2`, messageID: `` },
    { key: `barbarossaChannel3`, messageID: `` },
    { key: `barbarossaChannel4`, messageID: `` },
    { key: `barbarossaChannel5`, messageID: `` },
    { key: `barbarossaChannel6`, messageID: `` },
    { key: `barbarossaChannel7`, messageID: `` },
    { key: `barbarossaChannel8`, messageID: `` },
    { key: `barbarossaChannel9`, messageID: `` },
    { key: `barbarossaChannel10`, messageID: `` },
    { key: `barbarossaChannel11`, messageID: `` },
    { key: `barbarossaChannel12`, messageID: `` },
    { key: `barbarossaChannel13`, messageID: `` },
    { key: `barbarossaChannel14`, messageID: `` },
    { key: `barbarossaChannel15`, messageID: `` },
    { key: `barbarossaChannel16`, messageID: `` },

    // Culton
    { key: `cultonChannel1`, messageID: `` },
    { key: `cultonChannel2`, messageID: `` },
    { key: `cultonChannel3`, messageID: `` },
    { key: `cultonChannel4`, messageID: `` },
    { key: `cultonChannel5`, messageID: `` },
    { key: `cultonChannel6`, messageID: `` },
    { key: `cultonChannel7`, messageID: `` },
    { key: `cultonChannel8`, messageID: `` },

    // Devourer
    { key: `devourerChannel1`, messageID: `` },
    { key: `devourerChannel2`, messageID: `` },

    // Eva
    { key: `evaChannel1`, messageID: `` },
    { key: `evaChannel2`, messageID: `` },
    { key: `evaChannel3`, messageID: `` },
    { key: `evaChannel4`, messageID: `` },
    { key: `evaChannel5`, messageID: `` },
    { key: `evaChannel6`, messageID: `` },
    { key: `evaChannel7`, messageID: `` },
    { key: `evaChannel8`, messageID: `` },
    { key: `evaChannel9`, messageID: `` },
    { key: `evaChannel10`, messageID: `` },

    // Frost Bot
    { key: `frostbotChannel1`, messageID: `` },
    { key: `frostbotChannel2`, messageID: `` },
    { key: `frostbotChannel3`, messageID: `` },
    { key: `frostbotChannel4`, messageID: `` },
    { key: `frostbotChannel5`, messageID: `` },
    { key: `frostbotChannel6`, messageID: `` },
    { key: `frostbotChannel7`, messageID: `` },
    { key: `frostbotChannel8`, messageID: `` },
    { key: `frostbotChannel9`, messageID: `` },
    { key: `frostbotChannel10`, messageID: `` },
    { key: `frostbotChannel11`, messageID: `` },
    { key: `frostbotChannel12`, messageID: `` },
    { key: `frostbotChannel13`, messageID: `` },
    { key: `frostbotChannel14`, messageID: `` },
    { key: `frostbotChannel15`, messageID: `` },
    { key: `frostbotChannel16`, messageID: `` },

    // Haboela
    { key: `haboelaChannel1`, messageID: `` },
    { key: `haboelaChannel2`, messageID: `` },
    { key: `haboelaChannel3`, messageID: `` },
    { key: `haboelaChannel4`, messageID: `` },
    { key: `haboelaChannel5`, messageID: `` },
    { key: `haboelaChannel6`, messageID: `` },
    { key: `haboelaChannel7`, messageID: `` },
    { key: `haboelaChannel8`, messageID: `` },
    { key: `haboelaChannel9`, messageID: `` },
    { key: `haboelaChannel10`, messageID: `` },
    { key: `haboelaChannel11`, messageID: `` },
    { key: `haboelaChannel12`, messageID: `` },
    { key: `haboelaChannel13`, messageID: `` },
    { key: `haboelaChannel14`, messageID: `` },
    { key: `haboelaChannel15`, messageID: `` },
    { key: `haboelaChannel16`, messageID: `` },
    { key: `haboelaChannel17`, messageID: `` },
    { key: `haboelaChannel18`, messageID: `` },
    { key: `haboelaChannel19`, messageID: `` },
    { key: `haboelaChannel20`, messageID: `` },

    // Harrah
    { key: `harrahChannel1`, messageID: `` },
    { key: `harrahChannel2`, messageID: `` },
    { key: `harrahChannel3`, messageID: `` },
    { key: `harrahChannel4`, messageID: `` },
    { key: `harrahChannel5`, messageID: `` },
    { key: `harrahChannel6`, messageID: `` },
    { key: `harrahChannel7`, messageID: `` },
    { key: `harrahChannel8`, messageID: `` },

    // Interdimensional Frostfire Dragon
    { key: `dragonChannel1`, messageID: `` },
    { key: `dragonChannel2`, messageID: `` },

    // Lucia
    { key: `luciaChannel1`, messageID: `` },
    { key: `luciaChannel2`, messageID: `` },
    { key: `luciaChannel3`, messageID: `` },
    { key: `luciaChannel4`, messageID: `` },
    { key: `luciaChannel5`, messageID: `` },
    { key: `luciaChannel6`, messageID: `` },
    { key: `luciaChannel7`, messageID: `` },
    { key: `luciaChannel8`, messageID: `` },
    { key: `luciaChannel9`, messageID: `` },
    { key: `luciaChannel10`, messageID: `` },
    { key: `luciaChannel11`, messageID: `` },
    { key: `luciaChannel12`, messageID: `` },
    { key: `luciaChannel13`, messageID: `` },
    { key: `luciaChannel14`, messageID: `` },
    { key: `luciaChannel15`, messageID: `` },
    { key: `luciaChannel16`, messageID: `` },

    // Magma
    { key: `magmaChannel1`, messageID: `` },
    { key: `magmaChannel2`, messageID: `` },
    { key: `magmaChannel3`, messageID: `` },
    { key: `magmaChannel4`, messageID: `` },
    { key: `magmaChannel5`, messageID: `` },
    { key: `magmaChannel6`, messageID: `` },
    { key: `magmaChannel7`, messageID: `` },
    { key: `magmaChannel8`, messageID: `` },
    { key: `magmaChannel9`, messageID: `` },
    { key: `magmaChannel10`, messageID: `` },

    // Robarg
    { key: `robargChannel1`, messageID: `` },
    { key: `robargChannel2`, messageID: `` },
    { key: `robargChannel3`, messageID: `` },
    { key: `robargChannel4`, messageID: `` },
    { key: `robargChannel5`, messageID: `` },
    { key: `robargChannel6`, messageID: `` },
    { key: `robargChannel7`, messageID: `` },
    { key: `robargChannel8`, messageID: `` },
    { key: `robargChannel9`, messageID: `` },
    { key: `robargChannel10`, messageID: `` },
    { key: `robargChannel11`, messageID: `` },
    { key: `robargChannel12`, messageID: `` },
    { key: `robargChannel13`, messageID: `` },
    { key: `robargChannel14`, messageID: `` },
    { key: `robargChannel15`, messageID: `` },
    { key: `robargChannel16`, messageID: `` },

    // Rudolph
    { key: `rudolphChannel1`, messageID: `` },
    { key: `rudolphChannel2`, messageID: `` },
    { key: `rudolphChannel3`, messageID: `` },
    { key: `rudolphChannel4`, messageID: `` },
    { key: `rudolphChannel5`, messageID: `` },
    { key: `rudolphChannel6`, messageID: `` },
    { key: `rudolphChannel7`, messageID: `` },
    { key: `rudolphChannel8`, messageID: `` },
    { key: `rudolphChannel9`, messageID: `` },
    { key: `rudolphChannel10`, messageID: `` },

    // Scylla
    { key: `scyllaChannel1`, messageID: `` },
    { key: `scyllaChannel2`, messageID: `` },
    { key: `scyllaChannel3`, messageID: `` },
    { key: `scyllaChannel4`, messageID: `` },
    { key: `scyllaChannel5`, messageID: `` },
    { key: `scyllaChannel6`, messageID: `` },
    { key: `scyllaChannel7`, messageID: `` },
    { key: `scyllaChannel8`, messageID: `` },
    { key: `scyllaChannel9`, messageID: `` },
    { key: `scyllaChannel10`, messageID: `` },
    { key: `scyllaChannel11`, messageID: `` },
    { key: `scyllaChannel12`, messageID: `` },
    { key: `scyllaChannel13`, messageID: `` },
    { key: `scyllaChannel14`, messageID: `` },
    { key: `scyllaChannel16`, messageID: `` },
    { key: `scyllaChannel17`, messageID: `` },
    { key: `scyllaChannel18`, messageID: `` },
    { key: `scyllaChannel19`, messageID: `` },
    { key: `scyllaChannel20`, messageID: `` },


    // Sobek
    { key: `sobekChannel1`, messageID: `` },
    { key: `sobekChannel2`, messageID: `` },
    { key: `sobekChannel3`, messageID: `` },
    { key: `sobekChannel4`, messageID: `` },
    { key: `sobekChannel5`, messageID: `` },
    { key: `sobekChannel6`, messageID: `` },
    { key: `sobekChannel7`, messageID: `` },
    { key: `sobekChannel8`, messageID: `` },
    { key: `sobekChannel9`, messageID: `` },
    { key: `sobekChannel10`, messageID: `` },
    { key: `sobekChannel11`, messageID: `` },
    { key: `sobekChannel12`, messageID: `` },
    { key: `sobekChannel13`, messageID: `` },
    { key: `sobekChannel14`, messageID: `` },
    { key: `sobekChannel15`, messageID: `` },
    { key: `sobekChannel16`, messageID: `` }

]